version: '{branch}-{build}'

init:
  # Create our AppVeyor version
  - ps: $env:commit = $env:appveyor_repo_commit.SubString(0,7)
  - ps: Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch,$env:appveyor_build_number,$env:commit )

environment:
  VSVER: 14.0
  matrix:
    - MSVC_VERSION: 15
      RUNTIME_LINKAGE: static
      QT_VERSION: 5.8
      QT_LINKAGE: static
      ICU_VERSION: 57.1
      ICU_LINKAGE: static
      COVERITY_BUILD_CANDIDATE: True
      QTDIR: C:\Qt\5.8\msvc2015
      VCLIBS: UCRTBASED.dll

configuration:
  - release

install:
  # Set some vars
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - set 
  - set VCLIBDIR=%WINDIR%\SysWOW64 # Find vclibs
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe BUILD=release
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

#before_build:

build_script:
  - pwd
  - cd C:\projects\exposer-gui
  - pwd
  - git submodule init
  - git submodule update
  # Prepare the out-of-source build directory.
  - mkdir build
  - pwd
  - ls
  #- qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%
  - cd build
  - pwd
  - ls
  - cmake -G "NMake Makefiles" DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%QTDIR% .. #-H. -Bbuild .. #-DCMAKE_PREFIX_PATH=%QTDIR%
  #- cmake --build %APPVEYOR_BUILD_FOLDER%-build

  # Compile it and check for .exe
  #- cd %APPVEYOR_BUILD_FOLDER%-build
  - '%make%'
  - dir /b /s *.exe

after_build:
  # Add a link to the build output within the source directory. This is needed because AppVeyor does
  # not support extracting artifacts from out-of-source build directories. See 'artifacts' below.
  - dir /b /s *.exe
  - cd ..
  - mkdir deploy
  - copy build\exposer-gui.exe deploy\exposer-gui.exe
  - windeployqt --compiler-runtime deploy\exposer-gui.exe
  - for %%I in (%VCLIBS%) do copy %VCLIBDIR%\%%I deploy\
  - 7z a -tzip exposer_gui_%commit%.zip deploy -r
#  - copy build\exposer_gui_%commit%.zip %APPVEYOR_BUIL\exposer_gui_%commit%.zip
  - dir /b /s *.zip

artifacts:
  - path: exposer_gui_%commit%.zip
    name: exposer-gui
